site_name: Everything Resource Guide

theme:
  name: material
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: 切换到浅色模式
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight

markdown_extensions:
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - admonition

plugins:
  - search
  - awesome-pages

repo_url: https://github.com/Lyaiya/Everything-Resource-Guide
repo_name: Lyaiya/Everything-Resource-Guide
